language: python

sudo: true

os: linux

python:
    - "3.6"

services:
  - docker

matrix:
  allow_failures:
    - python: "3.6"

before_install:
  - sudo chmod u+x .travis/*
  - /bin/bash .travis/before_install

script:
  - /bin/bash .travis/script
